### ISSUE TITLE
Switch to ciscospark from csco-spark ?

### ISSUE THREAD

**Issue by jonfreedman** [tonybaloney/hubot-spark#2]
It looks like the ciscospark npm package is maintained by Cisco so may be a better choice unless it's missing features?

https://developer.ciscospark.com/sdk.html

**Comment by tonybaloney** [comment]
Cool! Yeah I'll take a look.

**Comment by tonybaloney** [comment]
For now, this module is closed source. And lacking some features this module requires like list messages since datetime. I will wait till they open it up
