### ISSUE TITLE
Replace calls to @robot.logger.info with @robot.logger.debug in standard code paths

### ISSUE THREAD

**Issue by jonfreedman** [tonybaloney/hubot-spark#3]
It seems excessively chatty to log on every message sent, let alone received

**Comment by tonybaloney** [comment]
Agreed. Will fix up

**Comment by tonybaloney** [comment]
https://github.com/tonybaloney/hubot-spark/commit/1a04154d6c5377898120a6d3f616c721d646c28d 
Fixed, new package 1.7.1
