### ISSUE TITLE
Heroku and hubot-spark

### ISSUE THREAD

**Issue by khanly** [tonybaloney/hubot-spark#4]
Hello.

I have no issue running heroku with campfire or locally on my mac with hubot-spark.
However, when I tried to run heroku with hubot-spark, I got this output error in heroku logs.

Please advise.

![screenshot 2016-05-10 20 56 08](https://cloud.githubusercontent.com/assets/9001717/15169641/55bc7442-16f2-11e6-82b1-54273ccaa2a6.png)

**Comment by tonybaloney** [comment]
the 3rd party dep for this module is a csco-spark npm module, the syntax error is here- https://github.com/drkchiloll/csco-spark/blob/master/lib/csco-spark.js#L14
The syntax in that module is requires NodeJS version 4+ as it utilizes some ES2015 (ES6) features not found in other versions of Node. Looks like heroku uses an older version of node, are you able to select a newer version?

**Comment by khanly** [comment]
I selected a newer version of NodeJS  and it worked.  Thank you!

**Comment by tonybaloney** [comment]
closing.
